# Churn prediction
Based on the blog https://medium.com/@pushkarmandot/build-your-first-deep-learning-neural-network-model-using-keras-in-python-a90b5864116d

In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

np.random.seed(301)

Using TensorFlow backend.


In [2]:
churn_data = pd.read_csv("Churn_Modelling.csv")

In [3]:
churn_data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
churn_data.tail()

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0

In [5]:
churn_data.shape

(10000, 14)

In [6]:
X = churn_data.iloc[:,3:13].values # .values converts this sliced df into ndarray
y = churn_data.iloc[:, 13].values

In [7]:
X[:,1] = LabelEncoder().fit_transform(X[:, 1])
X[:, 2] = LabelEncoder().fit_transform(X[:, 2])

In [8]:
X.shape

(10000, 10)

In [9]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [10]:
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [11]:
X.shape

(10000, 11)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [13]:
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size = 0.1)

In [14]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_val = sc.transform(X_val)

In [15]:
X_train

array([[ 1.72058015, -0.5739289 ,  1.8740067 , ..., -1.54384541,
        -1.03390789, -1.7242227 ],
       [-0.58119931, -0.5739289 ,  1.02986019, ...,  0.64773325,
        -1.03390789,  0.46619827],
       [-0.58119931, -0.5739289 ,  1.3008208 , ...,  0.64773325,
         0.96720415,  0.75196518],
       ...,
       [-0.58119931,  1.74237609,  0.85269364, ...,  0.64773325,
         0.96720415,  1.40718361],
       [-0.58119931,  1.74237609,  0.54004678, ...,  0.64773325,
        -1.03390789, -0.03853836],
       [-0.58119931, -0.5739289 ,  0.62341928, ..., -1.54384541,
        -1.03390789,  0.16871132]])

In [20]:
churner_nn = Sequential()
dense_classes = [15, 10, 5]
drops = [0.15, 0.1]
churner_nn.add(Dense(dense_classes[0], activation = 'relu', input_dim = 11))
churner_nn.add(Dropout(drops[1]))
churner_nn.add(Dense(dense_classes[1], activation = 'relu'))
churner_nn.add(Dropout(drops[1]))
churner_nn.add(Dense(dense_classes[1], activation = 'relu'))
churner_nn.add(Dropout(drops[1]))
churner_nn.add(Dense(dense_classes[2], activation = 'relu'))

In [21]:
churner_nn.add(Dense(output_dim = 1, activation = 'sigmoid'))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1)`
  """Entry point for launching an IPython kernel.


In [22]:
churner_nn.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [23]:
churner_nn.fit(X_train, y_train, batch_size = 100, nb_epoch = 70)

Instructions for updating:
Use tf.cast instead.


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/70
7200/7200 [==============================] - 1s 85us/step - loss: 0.5474 - acc: 0.7912
Epoch 2/70
7200/7200 [==============================] - 0s 11us/step - loss: 0.4885 - acc: 0.7918
Epoch 3/70
7200/7200 [==============================] - 0s 10us/step - loss: 0.4643 - acc: 0.7918
Epoch 4/70
7200/7200 [==============================] - 0s 10us/step - loss: 0.4569 - acc: 0.7918
Epoch 5/70
7200/7200 [==============================] - 0s 10us/step - loss: 0.4542 - acc: 0.7918
Epoch 6/70
7200/7200 [==============================] - 0s 11us/step - loss: 0.4513 - acc: 0.7918
Epoch 7/70
7200/7200 [==============================] - 0s 11us/step - loss: 0.4443 - acc: 0.7918
Epoch 8/70
7200/7200 [==============================] - 0s 11us/step - loss: 0.4456 - acc: 0.7918
Epoch 9/70
7200/7200 [==============================] - 0s 11us/step - loss: 0.4414 - acc: 0.7918
Epoch 10/70
7200/7200 [==============================] - 0s 11us/step - loss: 0.4425 - acc: 0.7918
Epoch 11/70
7200/72

In [24]:
y_pred_val = churner_nn.predict(X_val)
y_pred_val = (y_pred_val > 0.5)

In [25]:
cm1 = confusion_matrix(y_val, y_pred_val)

In [26]:
cm1

array([[600,  41],
       [ 75,  84]])

In [27]:
(cm1[0][0]+cm1[1][1])/cm1.sum()

0.855

In [28]:
y_pred_test = churner_nn.predict(X_test)
y_pred_test = (y_pred_test > 0.5)

In [29]:
cm2 = confusion_matrix(y_test, y_pred_test)

In [30]:
(cm2[0][0]+cm2[1][1])/cm2.sum()

0.866

In [31]:
cm2

array([[1537,   84],
       [ 184,  195]])

In [32]:
cm1

array([[600,  41],
       [ 75,  84]])

In [33]:
score1 = churner_nn.evaluate(X_val, y_val)

800/800 [==============================] - 0s 100us/step


In [34]:
score1

[0.34154426723718645, 0.855]

In [35]:
score2 = churner_nn.evaluate(X_test, y_test)

2000/2000 [==============================] - 0s 20us/step


In [36]:
score2

[0.33121792268753053, 0.866]